### ISSUE TITLE
Take advantage of Norder0,1 and 2

### ISSUE THREAD

**Issue by tboch** [cds-astro/aladin-lite#1]
Currently, Aladin Lite does not use Norder 0, 1 and 2 that are created for recent HiPS.
Using them would improve the user experience, preventing the gap in resolution we observe now between Allsky tiles and Norder3 tiles.

**Comment by tboch** [comment]
This would also mean the Allsky file is no more needed if Norder 0, 1 and 2 are present

**Comment by bmatthieu3** [comment]
I close this issue as aladin lite v3 is fetching order 0, 1, 2 tiles if possible.
