### ISSUE TITLE
possibility of changing scale (contrast) of the image

### ISSUE THREAD

**Issue by volodymyrss** [cds-astro/aladin-lite#10]
Hello,

first of all thanks a lot for making this amazing tool, among many others provided by CDS!

We'd like to include it in our project, but I found that one feature which is important for us does not seem to be available in the Aladin Light: the possibility to change the scale of the image in the interface. Surely it is possible to adjust the image before convering it to hips, but it's not interactive.
Is it really missing or I just did not find it?

I met Giuseppe Greco on Multi-Messenger ASTERICS conference and he told me that it could be possible to write a plugin to implement such a functionality. I'd be happy to try myself, if I knew were to start. 

Best Regards

Volodymyr SAVCHENKO

**Comment by tboch** [comment]
Hi @volodymyrss . I'm not sure I fully understand your need, could you elaborate your use case by giving for instance an example of what you would like to achieve?
Thanks!

**Comment by volodymyrss** [comment]
Our images are in phycally meaningfull units: signal-to-noise ratio, probability, flux. The dynamic range of these units is set by the convention and is physically motivated.

This dynamic range happens to be qute irregular. Often, a small range of the dynamic range contains a lot of information.
Mapping this physical dynamic range to colormap results in a lot of information in a small range of the colorbar, rendering it invisible by eye.

One typical case is when there are several very bright sources/pixels and a lot of faint ones. Mapping linearly from flux min-max to the colorbar results in a few bright dots visible and the rest is black.

We typically deal with this by adjusting the mapping from the physical units to the colormap.
One way is to make non-linear mapping, e.g. log or a powerlaw (its similar to gamma-correction).
And/or we may choose custom min-max physical values to map to the colormap. In this case, for example, everything above certain value will be mapped to the same color, the edge of the colormap.

we could do such a transformation before producing hips. but it would be very useful to adjust it interactively. it is because different adjustments reveal different information in the image, and user often wants to "play" with it, at the same time as adjusting  the color, or zoom and location,.

we are very used to this functionality in ds9, for example. it is also possible to do this in aladin (non-light).
which is why an interface without it feels incomplete.

**Comment by volodymyrss** [comment]
you added the tag, I interpret it as a possibility, right?

is there a way to contribute to this, writing a plugin? do you accept community contributions?

**Comment by tboch** [comment]
thank you for the explanations, that's perfectly clear now.
HiPS are typically generated with 2 set of tiles:
- FITS tiles which have the full dynamic range of the original images
- JPEG or PNG tiles for which a specific cut has been set, and used mainly by "basic" clients for visualisation

Currently, Aladin Lite only supports JPEG/PNG tiles but I want to try to support FITS tiles as to let user be able to control the contrast.

**Comment by bmatthieu3** [comment]
@volodymyrss - the new aladin lite version allows you to display fits files (and HiPS with fits tiles) and change contrast of the pixels (also apply a tranfer function). Does it satisfies your needs ?

**Comment by volodymyrss** [comment]
Thanks! Yes, it looks quite good indeed, and it might be the best option for us right now, so we'll try it both in https://github.com/oda-hub/dispatcher-app/issues/535 and in https://github.com/esg-epfl-apc/tools-astro/issues/3
