### ISSUE TITLE
Drawing a non-panning detector FOV indicator

### ISSUE THREAD

**Issue by elnjensen** [cds-astro/aladin-lite#105]
I'm trying to implement a feature to overlay the field of view of a given detector (i.e. a rectangle with a given angular width and height) on the Aladin view, and to allow the user to move the sky view to frame an observation.  This differs from the existing graphic overlay functionality in that the rectangle should stay centered on the window center (just as the reticle does) when the sky is panned.  However, the rectangle *should* be redrawn to change size when the view is zoomed in or out. 

A couple of questions: 
1. Does it make sense to use the existing reticle canvas to draw this?  In experimenting, I can draw a rectangle there, but it gets erased as soon as there is a mouse event.  Perhaps a separate canvas would be better. 
2. Does Aladin define events associated with zooming or panning?  Or would I need to tie into lower-level mouse events to determine when the user does these things? 

Thanks!

**Comment by bmatthieu3** [comment]
You are welcome. I prefer to close the issue. If other people do have an interest in that feature too I might consider to reopen it or open a new one. Also, if you have any questions feel free to open a new issue
