### ISSUE TITLE
OPening session with a non-black background 

### ISSUE THREAD

**Issue by lmichel** [cds-astro/aladin-lite#106]
With the default setting, when you open pointed survey (e.g. XMM) you get this:
 
![Capture d’écran de 2023-06-16 11-08-04](https://github.com/cds-astro/aladin-lite/assets/11462648/7848636d-6de9-48d4-8e2c-50ffb6f6099e)

It is difficult to discriminate what is covered by the survey and what is not.

If the default background color was very far from black, you will get immediately this :

![Capture d’écran de 2023-06-16 11-08-18](https://github.com/cds-astro/aladin-lite/assets/11462648/33cc5a97-0206-4e68-8ea8-952dcfa17726)

This would be a significant enhancement for pointed surveys without alteration for the all-sky surveys.

**Comment by ManonMarchand** [comment]
I vote for `rgb(178, 50, 178)` like the default reticle color, we need more pink/purple in the sky :)

**Comment by bmatthieu3** [comment]
@lmichel @ManonMarchand  - The JS API allow you to change the background color to the one you need. I do not think a specific saturated color is a good choice for the default font (the green/purple may not be adapted to another use case or survey, especially if the use case is just for visualizing outreach 'beautiful' images). On the contrary, I also agree black hide the border of surveys not covering the whole sky. I thus suggest to put a de-saturated color (gray), I think this is a good compromise among all the use cases and again, users can change it through the JS api ( See this issue: https://github.com/cds-astro/aladin-lite/issues/69 )

What do you think ?

**Comment by ManonMarchand** [comment]
Yes, a dark-ish gray as the default is also good :)

**Comment by bmatthieu3** [comment]
Especially see: https://github.com/cds-astro/aladin-lite/pull/85
There is an optional keyword: backgroundColor that you can set when initializing the aladin view.

**Comment by lmichel** [comment]
The suggestion is to have a default bkg color that allows users to identity areas that aren't covered without having to make any special adjustments.
I admit that my green is a bit controversial and that it can no be imposed to everybody. Grey is fine.
