### ISSUE TITLE
Add support for visualization of MOC perimeter

### ISSUE THREAD

**Issue by tboch** [cds-astro/aladin-lite#11]
Initial idea by @ggreco77

Implementation could be done mimicking the one in Aladin Desktop or drawing inspiration from [MOCPy border function](https://mocpy.readthedocs.io/en/latest/stubs/mocpy.MOC.html#mocpy.MOC.border)

**Comment by bmatthieu3** [comment]
Hi, that would be very nice to have indeed.

@fxpineau - How could I get the list of ra/dec describing the border of a MOC using moclibrust ?

**Comment by bmatthieu3** [comment]
It is possible to do that with the option keyword 'perimeter' when creating a new MOC with A.MOCFromUrl:

```js
var moc10 = A.MOCFromURL('https://alasky.unistra.fr/MocServer/query?ivorn=ivo%3A%2F%2FCDS%2FV%2F139%2Fsdss9&get=moc&order=9&fmt=fits', {color: '#ffffff', perimeter: true, fillColor: '#aabbcc', opacity: 0.1, lineWidth: 3});
```

This MOC object will soon be documented in the API doc https://cds-astro.github.io/aladin-lite/
