### ISSUE TITLE
Alpha chanel on color maps

### ISSUE THREAD

**Issue by lmichel** [cds-astro/aladin-lite#110]
The only way to see simultaneously 2 survey is to make this in foreground a bit transparent. 

This has 2 drawbacks:
- The background looks faded 
- the foreground has a low contrast.

![Capture d’écran de 2023-06-16 11-36-38](https://github.com/cds-astro/aladin-lite/assets/11462648/cf3e732f-88b6-42d9-989e-44a1b5c2c10e)
 
Overlaid with
 
![Capture d’écran de 2023-06-16 11-37-57](https://github.com/cds-astro/aladin-lite/assets/11462648/f5b775d2-5885-4e41-8e51-e95dc48ff0c5)

gives 
![Capture d’écran de 2023-06-16 11-38-25](https://github.com/cds-astro/aladin-lite/assets/11462648/6afe146e-b593-43c5-9010-a0c43c6a5e1a)

Not that bad but this can be improved.
This idea would be to allow the user to make all foreground pixels less bright that XXX transparent.
So that the foreground stars would remain visible as well as all the background features.

**Comment by bmatthieu3** [comment]
Maybe one workaround would be to use the additive blending mode in aladin lite. Follow the steps:
1. Choose DSS as the background layer
2. Overlay DSS with XMM (the foreground)
3. Set the blending mode of XMM from default to additive

It gives something like:
<img width="1287" alt="image" src="https://github.com/cds-astro/aladin-lite/assets/2772384/57e4ec11-2c96-45cc-9618-7876c74e638e">

Additive blending mode sums up the pixels. If you have black (r = 0, g = 0, b = 0) on top of any color, then you will get no difference. For high intensity, you will end up with a brighter final color.

Is it similar to what you have in mind ?

**Comment by bmatthieu3** [comment]
We should be able to switch survey layers from the user interface. It would be more flexible for the user to put the stack he wants in the good order. I will close this one but open another referring this one.

**Comment by lmichel** [comment]
Fine
