### ISSUE TITLE
HEALPix grid isn't valid for some targets

### ISSUE THREAD

**Issue by RobinMeneust** [cds-astro/aladin-lite#115]
On CDS/P/Mars/Viking-MDIM21-color at https://aladin.cds.unistra.fr/AladinLite/, the HEALPix grid is not moving the same way as in the previous version. It doesn't "follow" the HiPS, one of the axis is inverted:
![HEALPix grid issue](https://github.com/cds-astro/aladin-lite/assets/85349121/91b3546e-d0ef-44a6-9ff8-96b1f86528b5)

**Comment by ManonMarchand** [comment]
Thanks for spotting this! I can reproduce the bug

**Comment by bmatthieu3** [comment]
I pushed a fix by refactoring a little bit of code: specifically I directly added the test of 'longitude_reversed' in the projections methods. Thank you @RobinMeneust for the report.

**Comment by bmatthieu3** [comment]
I pushed a fix by refactoring a little bit of code: specifically I directly added the test of 'longitude_reversed' in the projections methods. Thank you @RobinMeneust for the report.
