### ISSUE TITLE
Catalogues flashing on and off

### ISSUE THREAD

**Issue by raphaelshirley** [cds-astro/aladin-lite#12]
Hi,

I'm really happy that you are making the code available on GitHub. It is a great project and more documentation will make it easier for casual users such as me to make websites with it.

I am using Aladin Lite to show HiPS catalogues and am getting an effect where when I zoom in. Objects appear to flash on and off then disappear. I thought this might be to do with how I was making the HiPS (with hipsgen-cat.jar) but I think I can see a similar effect for the GAIA-DR2 release.

Example can be seen zooming into a region with dense objects here:

http://hedam.lam.fr/HELP/dataproducts/dmu31/dmu31_HiPS/data/help_dr1_alist/

Also other strange effects like clicking on an object makes objects disappear. The webpage is getting a lot of 404 errors for tsv files that aren't there. Perhaps it looks for all tiles and they are missing if there are no objects in the tile?

Otherwise, great work with this, it is excellent to have an easy to use tool for displaying your images and catalogues.

The full project I am working on is here for reference:

http://hedam.lam.fr/HELP/dataproducts/dmu31/dmu31_HiPS/viewer/

Many thanks,

Raphael.

UPDATE: This behaviour seems to happen in Chrome but not Firefox.

**Comment by blnkt** [comment]
Seems to be an issue regardless of which browser (screen capture is from firefox)
https://user-images.githubusercontent.com/8166060/109893476-9422ec80-7c40-11eb-8fa0-4d78ff2e5c93.mov

**Comment by bmatthieu3** [comment]
This has been solved in the aladin lite v3. It was an issue in the LRU Cache we have coded (in Utils.js)
