### ISSUE TITLE
Circle overlays do not appear drawn with the correct radius

### ISSUE THREAD

**Issue by C-Kan-42** [cds-astro/aladin-lite#126]
When drawing circle overlays, sometimes the circle doesn’t seem to appear with the correct radius. I’ve tested this here: https://aladin.cds.unistra.fr/AladinLite/doc/API/examples/footprints/, replacing the JavaScript code with this instead:
 
```
var aladin;
A.init.then(() => {
    aladin = A.aladin('#aladin-lite-div', {target: 'M 1', fov: 180});
 
    var overlay = A.graphicOverlay({color: '#ee2345', lineWidth: 3});
    aladin.addOverlay(overlay);
    overlay.add(A.circle(83.66067, 0, 30, {color: 'cyan'})); // radius in degrees
    var cat = A.catalog({name: 'Some markers', sourceSize: 18});
    aladin.addCatalog(cat);
    cat.addSources([A.marker(83, 29, {popupTitle: 'Point1', popupDesc: 'Does not show up in circle'})]);
});
 
```
Is this normal behavior for circle overlays?

**Comment by bmatthieu3** [comment]
Hi C-Kan-42,

You are right this is a strange behaviour. Now the source always lie in the circle. I noticed there is still sometimes a shift of the overlay w.r.t to the source but it is way more acceptable I would say.
You can test it as it is deployed on the beta version here: https://aladin.cds.unistra.fr/AladinLite/api/v3/beta/aladin.js
and tell us if it is good for you.

**Comment by C-Kan-42** [comment]
Yes, this is much better, thank you!
