### ISSUE TITLE
Error compiling 3.2.0

### ISSUE THREAD

**Issue by ghansham** [cds-astro/aladin-lite#129]
Software Configuration:

Node: 20.9.0
NPM: 8.11.0
Cargo: 1.73.0
Got following error while compiling version 3.2.0. This happens in 3.1.1 as well.

Compiling al-api v0.1.0 (C:\Users\Neena\Documents\sunny\astro\aladin-lite-3.2.0\src\core\al-api)
error[E0119]: conflicting implementations of trait `TryFrom<wasm_bindgen::JsValue>` for type `ColorRGB`
  --> al-api\src\color.rs:16:1
   |
16 | #[wasm_bindgen]
   | ^^^^^^^^^^^^^^^ conflicting implementation for `ColorRGB`
...
73 | impl TryFrom<JsValue> for ColorRGB {
   | ---------------------------------- first implementation here
   |
   = note: this error originates in the attribute macro `wasm_bindgen` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0119]: conflicting implementations of trait `TryFrom<wasm_bindgen::JsValue>` for type `ColorRGBA`
  --> al-api\src\color.rs:26:1
   |
26 | #[wasm_bindgen]
   | ^^^^^^^^^^^^^^^ conflicting implementation for `ColorRGBA`
...
86 | impl TryFrom<JsValue> for ColorRGBA {
   | ----------------------------------- first implementation here
   |
   = note: this error originates in the attribute macro `wasm_bindgen` (in Nightly builds, run with -Z macro-backtrace for more info)

Please guide.

regards
Ghansham

**Comment by bmatthieu3** [comment]
Hi @ghansham ,
Are you compiling in rust nightly ? If so maybe try to compile in stable version (cmd: rustup default stable)

**Comment by ghansham** [comment]
Hi,

Thanks a lot for the response.

I am using stable version only.
Cargo: 1.73.0 (2023-08-26)
rustup: 1.26.0 (2023-04-05)
rustc: 1.73.0 (2023-10-03)
wasm-bindgen (0.2.88)
wasm-pack (0.12.01)

Output of the command that you sent is:
info: using existing install for 'stable-x86-64-unknown-linux-gnu'
info: default toolchain set to 'stable-x86-64-unknown-linux-gnu'
stable-x86-64-unknown-linux-gnu unchanged- rustc 1.73.0 (cc66ad468 2023-10-03)

My os is Centos 8.2:
Centos Linux release 8.2.2004 (Core)

One more query is  how to setup HiPS server on an air gaped network (internet less environment)?


regards
Ghansham

**Comment by bmatthieu3** [comment]
Which command are you running ? You have to be on the develop branch. Then, npm install and npm run build/serve is the way to go

**Comment by tboch** [comment]
> One more query is how to setup HiPS server on an air gaped network (internet less environment)? Do we have the fits files corresponding to the HiPS hosted by servers. I am aware of hipstofits but that may not allow to download full coverage and that too with limited size option. Am I correct?

Could you elaborate on this? Do you want to copy a specific HiPS for usage without internet?

**Comment by ghansham** [comment]
Yes working in an internet-less system. Tried at my end to use wget to download an example hips and used simple http server to work on that. Is that the correct way?

**Comment by bmatthieu3** [comment]
Hi @ghansham , did you manage to fix your compiling errors ? You can as explained in #137 :

* upgrading your wasm-pack version
* removing your src/core/Cargo.lock and src/core/target
* relaunching a npm run build ?

**Comment by ghansham** [comment]
Right now bust. Will try later and update you.

**Comment by bmatthieu3** [comment]
Ok I will close that issue as @szpetny make it compile. I also updated the readme here: edef47e8b79e987f131451f9efb70810dd9be295

to give more insights if you have troubles with the rust compilation. You can reopen it if you have still problems.
