### ISSUE TITLE
Missing segments for display of MOC in wide FOV for SIN projection

### ISSUE THREAD

**Issue by ManonMarchand** [cds-astro/aladin-lite#133]
There are issues with the display of moc cells borders in slant orthographic projection. Segments close to the sides do disappear, and some cells in the middle are not closed. See here for an example on SDSS footprint: 

https://vizier.cds.unistra.fr/vizier/cat/aladinLite.html?V/154

**Comment by bmatthieu3** [comment]
I fixed it. it is on develop and should be released soon
