### ISSUE TITLE
Wrong HIPS displayed and no coordinate frame given. 

### ISSUE THREAD

**Issue by havok2063** [cds-astro/aladin-lite#134]
I am using the `npm`-installed version of AladinLite (package version 3.2.0), embedding it into a front-end project.  I am trying to set it to display the PanSTARRS color image as the base survey, with coordinates in decimal degrees.

I'm loading the app like so
```
<script lang="ts" setup type="module">

import A from 'aladin-lite'

let aladin = null

A.init.then(() => {
    aladin = A.aladin('#aladin-lite-div', {target: '2.67597, 57.74156', fov: 0.1, survey: "P/PanSTARRS/DR1/color-z-zg-g", projection: "AIT", cooFrame: 'ICRSd', showCooGridControl: true,
    showSimbadPointerControl: true, showCooGrid: false, showProjectionControl: false, showFullscreenControl: false});

    aladin.setFovRange(0.01, 10)
});
```
however when I load the page, it seems like the aladinlite loads the default DSScolor survey.  In the dropdown menu it displays the full url `https://alasky.u-strasbg.fr/DSS/DSSColor/` rather than the `DSS colored` selection.

I also see the following warning regarding coordinate frames, in the dev console, `No cooframe given. Coordinate systems supported: "ICRS", "ICRSd", "j2000" or "galactic". ICRS is chosen by default`, even though I have it set to "ICRSd".  

If I try to select the PS1 color survey, it does not load, and I see this error in the console
```
Uncaught (in promise) Error: invalid type: unit value, expected u8
    __wbindgen_error_new aladin.js:11558
```
However if I input the same settings at this site, https://aladin.cds.unistra.fr/AladinLite/doc/API/examples/AL-in-responsive-div/, it works properly.  Any ideas on what could be going on?

**Comment by tboch** [comment]
@bmatthieu3 : this looks very similar to the problem we fixed together last week. 
I think we should issue a new npm version shortly.

@havok2063 : would you mind copy/paste the network tab output from the developer's tools?

**Comment by havok2063** [comment]
@tboch Yeah, I wasn't sure the best way to copy it in. Here's a screenshot and an output json file of the network activity details.
<img width="1656" alt="aladinlite_network" src="https://github.com/cds-astro/aladin-lite/assets/1836302/d46f821d-afda-4743-88a6-9ecc7af3d463">
[aladinlite_network.json](https://github.com/cds-astro/aladin-lite/files/14127231/aladinlite_network.json)

**Comment by tboch** [comment]
Thanks!
The requests is list is filtered with "ala" keyword, could you also send the unfiltered list.I am interested in the requests to localhost.

**Comment by havok2063** [comment]
@tboch Yeah sure.  Here is the full network file.  There are 217 requests so it's hard to capture all that in a screenshot. If you want me to filter on anything, let me know.  
[aladinlite_full_network.json](https://github.com/cds-astro/aladin-lite/files/14141931/aladinlite_full_network.json)

**Comment by tboch** [comment]
@bmatthieu3 : the network log shows that this is the same problem that we had with the Fink portal.
Could you publish a new beta that @havok2063 could test in his app?

**Comment by havok2063** [comment]
@tboch Great to hear it might already be fixed.  Just curious, what is/was the original problem?

**Comment by havok2063** [comment]
@tboch @bmatthieu3 what's the status of getting a new version bump up on npm?

**Comment by ManonMarchand** [comment]
There is a beta version for 3.3 on npm if you want to try

**Comment by havok2063** [comment]
Thanks, it seems to be working so far.  The behavior is as expected and I no longer see any of the errors/warnings in the console.  Any idea on when there will be an official release of 3.3?

**Comment by havok2063** [comment]
And just to verify that things look ok, this is the correct UI? 

<img width="424" alt="Screenshot 2024-03-06 at 5 05 23 PM" src="https://github.com/cds-astro/aladin-lite/assets/1836302/52cd6219-98b6-4b87-ab6e-e1a1257fc27a">

**Comment by bmatthieu3** [comment]
@havok2063 - It will be released soon. It is good you did spot those issues (the UI one and the fovRange missing one which I suspect was not working since quite a long time from now) because I can fix them before the official release. We are also doing some tests regarding the integration of the 3.3 in ipyaladin (for running inside notebooks). Once those things will be fixed, I will do a release. I wanted to do it this week but it may gonna be for next week instead.

Keep in mind that if something still goes wrong when the official release will be out, you still can switch back to an older version here https://aladin.cds.unistra.fr/AladinLite/doc/release/ or for your case, an older npm package the time for us to fix the thing.

**Comment by havok2063** [comment]
@bmatthieu3 Sounds good!  Thanks a lot!
