### ISSUE TITLE
Fits images with positive CDELT1 value are not displayed

### ISSUE THREAD

**Issue by dsavchenko** [cds-astro/aladin-lite#136]
[Here](https://box.in2p3.fr/index.php/s/TnWCJMSC55XyipQ) is an example of the fits image that's not displayed.
It is created from scratch, using astropy. DS9 and fv read and display it properly.

The aladin-lite seems to recognise the WCS in the header (the view gets panned and zoomed to the proper sky region), but there is no image displayed regardless of the image settings (colormap etc.)
There isn't any unexpected output in the JS console. 

Tried both https://aladin.cds.unistra.fr/AladinLite/ and an embedded instance.

**Comment by ManonMarchand** [comment]
I can reproduce a strange behavior. The fits file does appear with these parameters though: 

https://aladin.cds.unistra.fr/AladinLite/?target=17%2016%2002.275-15%2002%2022.48&fov=360.00&survey=CDS%2FP%2FDSS2%2Fcolor

Speculative thoughts:
- that's a huge field of view (10°x10°) for a single source. Is there something strange with the WCS?
- maybe something to do with the PV value at 45°? The default is 90° so maybe there's something to explore there on our side

**Comment by ManonMarchand** [comment]
May also be related to : https://github.com/cds-astro/aladin-lite/issues/120 
There are issues with the Airy projection in aladin. If you make your fits image from scratch, can you try to convert it within astropy to one of the projection with no red crosses in the linked issue?

**Comment by dsavchenko** [comment]
Thank you, @ManonMarchand, for your replies. 

Seems that the problem isn't connected with WCS. Here is an [example of another image](https://box.in2p3.fr/index.php/s/qQByz33pHiTBYoT) that is created the same way but using a CAR projection, and aladin-lite either doesn't show it. 

The point worth notice is that the value of the "max cut" in the layer settings is automatically set to 15 whereas the actual maximal value in the image is ~50. Probably, this somehow related to the datatype (however, I tried to save the same image with different dtypes, neither worked).

**Comment by ManonMarchand** [comment]
Thanks for trying. Would you mind sharing the astropy snippet you wrote to create these fits images?

@bmatthieu3 : Tweaks on maxCut does not change the output

**Comment by dsavchenko** [comment]
Got it! The images that aren't shown properly, the value of `CDELT1` is positive. With negative value of it (so RA coordinate has conventional direction), everything works.

**Comment by bmatthieu3** [comment]
hi @dsavchenko - I fixed that, it was related to the webgl display method that do not draw triangles that are "backfacing" the view. I am using this culling backfacing to detect when triangles are crossing the view for specific allsky projections (aitoff, mercator) and hence I do not draw them.

I close this commit. The new beta/release versions that will be released will appear on this page: https://aladin.cds.unistra.fr/AladinLite/doc/release/
