### ISSUE TITLE
setFovRange removed?

### ISSUE THREAD

**Issue by havok2063** [cds-astro/aladin-lite#138]
This page, https://aladin.cds.unistra.fr/AladinLite/doc/API/#examples-list, documents `aladin.setFovRange(<min-fov-in-degrees>, <max-fov-in-degrees>) allows to restrict the field of view range.`.  However, this method doesn't appear to work in the application.   And it doesn't appear in the new docs here, https://cds-astro.github.io/aladin-lite/Aladin.html.   Has this method been deprecated?  If so, is there a new way to set the FoV limit?   I've seen this issue in versions 3.2 and 3.3.1-beta.

**Comment by bmatthieu3** [comment]
Hi @havok2063 , I suspect this is a feature missing for a long time from now. What is the use case for you to use it just to know ?

**Comment by havok2063** [comment]
Hi @bmatthieu3 my use case is for postage stamp views of single targets.  I'd like to limit the view range and other features to keep the app instance focused around the given target.  Like limiting the FOV to within ~0.5-1 degree around the target, something like that.  I have another instance of the app for full sky exploration.

**Comment by havok2063** [comment]
@bmatthieu3 Great, thanks!
