### ISSUE TITLE
control position of FOV label

### ISSUE THREAD

**Issue by havok2063** [cds-astro/aladin-lite#139]
The FOV label used to be at the bottom and now in 3.3, it's at the top.  This doesn't work when using aladin-lite for small postage stamp views.   See the attached image.  It would be great to have new options for controlling the position of the FOV label, like `"fovLabelPositiion": "topRight"` or `bottomLeft`.  For my case, I'd like to be able re-position the label in the bottom left or right corner.  The size of the label also looks quite large, so maybe there should also be a `fovLabelSize` that accepts some pixel value.

Or maybe the whole status bar at the top just needs some improvement on how it looks in small views?

<img width="424" alt="Screenshot 2024-03-06 at 5 05 23 PM" src="https://github.com/cds-astro/aladin-lite/assets/1836302/f6723611-f7b5-437e-8fde-4f9becedb5af">

**Comment by bmatthieu3** [comment]
You should be able to reposition the elements now: css classes you can redefine are listed here: https://cds-astro.github.io/aladin-lite/global.html#AladinOptions

**Comment by bmatthieu3** [comment]
I deployed a new 3.3.x-beta npm package that you can try. Here is an example that:
* move the cooFrame UI part somewhere else
* create a button at the bottom left of the view

```html
<!doctype html>
<html>
<head>
</head>
<body>


<div id="aladin-lite-div" style="width: 1024px; height: 768px"></div>

<script type="module">
    import A from '../src/js/A.js';
    let aladin;
    A.init.then(() => {
        var aladin = A.aladin(
            '#aladin-lite-div',
            {
                survey: 'P/allWISE/color', // set initial image survey
                projection: 'AIT', // set a projection
                fov: 1.5, // initial field of view in degrees
                target: 'NGC 2175', // initial target
                cooFrame: 'icrs', // set galactic frame
                reticleColor: '#ff89ff', // change reticle color
                reticleSize: 64, // change reticle size
                showContextMenu: true,
            }
        );

        let btn = A.button({
            content: 'My button',
            classList: ['myButton'],
            tooltip: {cssStyle: {color: 'red'}, content: 'Create a moc in pink!', position: {direction: 'top'}},
            action(o) {
                aladin.select('poly', p => {
                    try {
                        let ra = []
                        let dec = []
                        for (const v of p.vertices) {
                            let [lon, lat] = aladin.pix2world(v.x, v.y);
                            ra.push(lon)
                            dec.push(lat)
                        }

                        let moc = A.MOCFromPolygon(
                            {ra, dec},
                            {name: 'poly', lineWidth: 3.0, color: 'pink'},
                        );
                        aladin.addMOC(moc)
                    } catch(_) {
                        alert('Selection covers a region out of the projection definition domain.');
                    }
                })
            }
        });

        aladin.addUI(btn)
    });
</script>
<style>
    .aladin-cooFrame {
        position: absolute;
        top: 10rem;
    }

    .myButton {
        position: absolute;
        bottom: 0;
        left: 0;

        background-color: pink;
    }
</style>
</body>
</html>

```

**Comment by bmatthieu3** [comment]
@havok2063 - Is it working as you want or you still have some troubles/questions ? Thank you

**Comment by havok2063** [comment]
Yes I believe so.  I was able to move the FOV field to the bottom left using the following syntax.  I had to add the `!important` flag to override the defaults.  
```
<style>
.aladin-fov {
    position: absolute;
    top: 16rem !important;
    left: 0rem !important;
}
</style>
```

**Comment by bmatthieu3** [comment]
Ok thanks, let me close that issue for the moment. Maybe I can manage later for you to not use that `!important` flag.
