### ISSUE TITLE
The cog menu missing in the newest beta(alpha?)

### ISSUE THREAD

**Issue by szpetny** [cds-astro/aladin-lite#141]
Example:
https://jsfiddle.net/rvx82p13/4/

In the newest version it looks like the menu with the cog icon disappeared completely.

![image](https://github.com/cds-astro/aladin-lite/assets/12716399/7de257b4-d530-4dc7-b560-c62b0f2cac1c)

**Comment by bmatthieu3** [comment]
You can enable it in the init options, it is the showSettingsControl: true, I prefer to disable it by default.

**Comment by szpetny** [comment]
ok sorry and thanks xD

**Comment by bmatthieu3** [comment]
no problems, the new api doc is in progress so not with all infos haha
