### ISSUE TITLE
support STC-S footprints

### ISSUE THREAD

**Issue by fstalm** [cds-astro/aladin-lite#146]
Support the drawing of footprints as they get returned in s_region columns of VOTables.

**Comment by ManonMarchand** [comment]
Hi, 
I transferred this issue from ipyaladin. I think it makes more sense to broaden the support of stc-s here that implement this downstream?

**Comment by bmatthieu3** [comment]
This is implemented. Votable now having a s_region column parse the STC-S string inside to define visualizable footprints.
