### ISSUE TITLE
erratic behaviour when div height is a percentage

### ISSUE THREAD

**Issue by havok2063** [cds-astro/aladin-lite#148]
Using aladin-lite 3.3.3-beta, when loading a full screen version of the app, with div height at 100%, I am seeing erratic behavior where the view screen scrolls, as if a movie or some auto-navigation is playing.  Additionally, some of the menu options cannot be selected.  The menu opens and immediately closes.  Attached is a video showing the behavior.   When I refresh the screen and load the app centered on target M101, the view screen automatically moves upwards.  The survey overlays and projection menus don't persist to select any of the options.   I also include the code snippet.   If I change the height to a pixel or vh value, e.g `500px` or `100vh` everything works as expected.  

https://github.com/cds-astro/aladin-lite/assets/1836302/fa6fff87-13a0-45fc-8923-2b18945ff432

```
<template>
    <div id="explore-aladin-lite" style="width: 100%; height: 100%"></div>
</template>

<script lang="ts" setup>
import A from 'aladin-lite'

let aladin = null

A.init.then(() => {
    aladin = A.aladin('#explore-aladin-lite', {target: 'M101', fov: 5, projection: "AIT",
    cooFrame: 'ICRSd', showCooGridControl: true, showSimbadPointerControl: true,
    showCooGrid: true});
});

</script>
```

**Comment by bmatthieu3** [comment]
Hi @havok2063,

Thanks, I can reproduce it on my side, I will investigate that. For the moment it seems that you can use the 100vh notation.

**Comment by bmatthieu3** [comment]
I fixed the problem. As the height refers to the parent div, if you specify no size for the body and html elements then the height will be of 150px because by default the canvas height is set to that. I strongly recommend using 100vh or settings the body and html's css to height: 100% too. A new latest version and npm package will be release this monday.

**Comment by havok2063** [comment]
Thanks @bmatthieu3 for looking into it.  That all makes sense.
