### ISSUE TITLE
Read Moc.fits to avoid unnecessary tiles retrieval requests

### ISSUE THREAD

**Issue by tboch** [cds-astro/aladin-lite#15]
By reading the Moc.fits file associated to a HiPS, Aladin Lite will be able to avoid trying to retrieve tiles in regions not covered by the HiPS.

**Comment by bmatthieu3** [comment]
This has been implemented in last version of aladin lite. Still the old behaviour is there while the MOC has not been fully fetched! Whenever the MOC is received, it is used for tile fetching.
