### ISSUE TITLE
MOC load error on MOCs with complicated perimeters

### ISSUE THREAD

**Issue by ManonMarchand** [cds-astro/aladin-lite#150]
Since v3.3.0, I have the following error when calling `MOCFromJSON`: 

```
MOC load error:Error: recursive use of an object detected which would lead to unsafe aliasing in rust
```

On MOCs with complicated perimeters. See for example this MOC [moc.zip](https://seafile.unistra.fr/f/02a2e45fc33d44278580/?dl=1) that triggers the error.

**Comment by ManonMarchand** [comment]
Note: It was working with version 3.2

**Comment by bmatthieu3** [comment]
https://github.com/cds-astro/cds-moc-rust/pull/8 should fix that again and keep the ability to render a MOC perimeter (not only full cells as it was the case in previous versions)

**Comment by bmatthieu3** [comment]
@ManonMarchand - the moc you give now works in develop so I can close the issue. There are some rendering artifacts as I do not subdivide enough some cells but I think this is for another improvement issue.
