### ISSUE TITLE
Old layout or new layout?

### ISSUE THREAD

**Issue by Firestar-Reimu** [cds-astro/aladin-lite#152]
Yesterday I look at aladin and the layout is this:

![aladin-4](https://github.com/cds-astro/aladin-lite/assets/65082432/996260e2-1c28-42a7-b071-b2b4ca58d508)

I can click a `(i) See more` to see the information and coverage of the survey

![1](https://github.com/cds-astro/aladin-lite/assets/65082432/b11f7d05-7c43-433e-b475-d8457cf0e707)

but today the https://aladin.cds.unistra.fr/AladinLite/ look like this

![屏幕截图_20240426_145820](https://github.com/cds-astro/aladin-lite/assets/65082432/5cc0127c-b3e5-4856-8870-eaefba095eb4)

and I cannot found `(i) See more`

**Comment by ManonMarchand** [comment]
Strange, did you go by mistake on the dev version of the webpage ? https://aladin.cds.unistra.fr/AladinLite/index_dev.gml 

Anyhow, `See more` is a new feature so the fact the it was not there on the 3.3.0 showcase page is normal.

**Comment by ManonMarchand** [comment]
You might also find this page useful if you need to learn more about the survey's coverage : https://aladin.cds.unistra.fr/hips/list

**Comment by bmatthieu3** [comment]
@Firestar-Reimu - The version you saw deployed is the current beta but is not that mature to be the version used for the portal. There will be a new one soon with something similar to the see more feature, mainly when you are searching for a new HiPS survey to add. There will be a new HiPS browser panel when you will want to add a new survey and this panel will have that 'see more' feature.

**Comment by bmatthieu3** [comment]
I added a similar feature in the beta version of aladin lite. There is a new HiPS browser window that does have this info button (i) to jump you to the page presenting the HiPS:

<img width="1128" alt="image" src="https://github.com/user-attachments/assets/a5690589-b236-4910-a3b4-75459ebd2dfb">

That HiPS browser box has a filter allowing you to filter HiPS by angular pixel resolution, observational regime or spatial (those that are inside the current viewport). It is still in development, we would like to add vignettes of HiPS matching the user query.
