### ISSUE TITLE
Zoom-out question

### ISSUE THREAD

**Issue by szpetny** [cds-astro/aladin-lite#153]
Hi guys,

In the older version of Aladin the user could do full zoom out, like this: 

![image](https://github.com/cds-astro/aladin-lite/assets/12716399/3fd507c7-bcfe-4f6c-a09b-465d68faca75)

Currently by default it is impossible, even the full sphere does not fit in the frame.

![image](https://github.com/cds-astro/aladin-lite/assets/12716399/c41b4dc4-37c6-416e-8587-f6899cf5ce6f)

Is it configurable (but I cannot find it)? Or perhaps you could add it back if it is gone?

**Comment by tboch** [comment]
I agree, this is a regression, it should be added back

**Comment by bmatthieu3** [comment]
Yes I confirm it will be added back.

**Comment by bmatthieu3** [comment]
Fixed in [9b098fd](https://github.com/cds-astro/aladin-lite/commit/9b098fdcddcb8e722b2b8a455d226fbbd2ce5c5f)
