### ISSUE TITLE
Serialize a MOC

### ISSUE THREAD

**Issue by bmatthieu3** [cds-astro/aladin-lite#154]
add a serialize method to the MOC class to return a serialization in json, ascii or fits, so that user can save it locally.

**Comment by ManonMarchand** [comment]
Why don't we recommend the use of mocpy instead?

**Comment by bmatthieu3** [comment]
That would be nice to save a MOC as a file directly from the aladin lite ui, especially those that we draw from the interface.

**Comment by ManonMarchand** [comment]
Got it. Something like a method `aladin.get_moc(name_of_the_moc)` then :slightly_smiling_face:

**Comment by ManonMarchand** [comment]
Oh sorry. Thought we were in the ipyaladin repo

**Comment by bmatthieu3** [comment]
@rhaigron - I merged this feature in the latest beta: https://aladin.cds.unistra.fr/AladinLite/api/v3/3.4.3-beta/aladin.js

There is now a download button you can click on to download the moc in json format:

![image](https://github.com/user-attachments/assets/a32b7dd4-8603-41b7-b4cb-b7d620f23670)
