### ISSUE TITLE
Deprecated RADECSYS for Aladin#getViewWCS

### ISSUE THREAD

**Issue by Xen0Xys** [cds-astro/aladin-lite#158]
The RADECSYS field needs to be changed to RADESYS or RADESYSa when recovering WCS from AL.

I also link this issue to the ipyaladin PR that discovered this: https://github.com/cds-astro/ipyaladin/pull/89

**Comment by ManonMarchand** [comment]
For reference, the deprecation is mentionned in table 22 of the (latest to this day) [fits standard document](https://fits.gsfc.nasa.gov/standard40/fits_standard40aa-le.pdf)
