### ISSUE TITLE
document class methods for the API

### ISSUE THREAD

**Issue by havok2063** [cds-astro/aladin-lite#186]
Is it possible to document the available public methods for object classes on the API?  For example, the documentation for a Catalog, https://cds-astro.github.io/aladin-lite/Catalog.html, does not show any of the available methods.  Currently you have to navigate the source code to find them.  This makes it challenging to figure out how to develop programmatically.

**Comment by bmatthieu3** [comment]
Sure the documentation has to be completed. Main important types I see are: Catalog, Image, HiPS, GraphicOverlay, MOC

**Comment by bmatthieu3** [comment]
I added the documentation of the public methods for Catalog, Image, HiPS, GraphicOverlay, MOC classes.

**Comment by havok2063** [comment]
Thank you!  It's very helpful!
