### ISSUE TITLE
Support of VOTable binary serialization

### ISSUE THREAD

**Issue by tboch** [cds-astro/aladin-lite#197]
Current version of Aladin Lite has a poor support of VOTable encoded as binary.
Loading such a VOTable results in truncated coordinates, all sources located in a single point.

<img width="367" alt="Capture d’écran 2024-10-02 à 09 52 15" src="https://github.com/user-attachments/assets/13df3ad7-cd30-40e9-b6ef-69044eb32570">

Sample VOTable file for testing (needs to be uncompressed first):
[gaia-sample.vot.zip](https://github.com/user-attachments/files/17221572/gaia-sample.vot.zip)

**Comment by bmatthieu3** [comment]
[84f998a](https://github.com/cds-astro/aladin-lite/commit/84f998afb8a333014af28ee2b4d1f9498f8f1d87) fixes that
