### ISSUE TITLE
Spurious tiles displayed

### ISSUE THREAD

**Issue by vforchi** [cds-astro/aladin-lite#20]
If the hips does not cover the whole sky and if you zoom out, aladin displays some spurious tiles on the borders, like this:
![Screen Shot 2019-12-02 at 13 34 45](https://user-images.githubusercontent.com/10163979/69959945-8ac04700-1508-11ea-93a4-6c6e7d90cc70.png)
I occasionally saw tiles being displayed in the wrong place, e.g. outside of the footprint of the HiPS, but I cannot reproduce this consistently.

**Comment by tboch** [comment]
Hi @vforchi 
I think this is related to AL display algorithm. The additional tiles are actually (huge) pixels from the Allsky file. The Allsky file should not be displayed if all tiles of the current view are available.
Thanks for the report.

**Comment by vforchi** [comment]
I don't know if this is related, but I just saw this:
![Screen Shot 2020-01-15 at 09 53 53](https://user-images.githubusercontent.com/10163979/72419461-289c6800-377d-11ea-8508-fa02033009d1.png)

**Comment by tboch** [comment]
> I don't know if this is related, but I just saw this:
> ![Screen Shot 2020-01-15 at 09 53 53](https://user-images.githubusercontent.com/10163979/72419461-289c6800-377d-11ea-8508-fa02033009d1.png)

This is unexpected indeed! Do you have a way to reproduce it?

**Comment by tboch** [comment]
> If the hips does not cover the whole sky and if you zoom out, aladin displays some spurious tiles on the borders, like this:
> ![Screen Shot 2019-12-02 at 13 34 45](https://user-images.githubusercontent.com/10163979/69959945-8ac04700-1508-11ea-93a4-6c6e7d90cc70.png)
> I occasionally saw tiles being displayed in the wrong place, e.g. outside of the footprint of the HiPS, but I cannot reproduce this consistently.

One easy way to circumvent this problem is to modify this line https://github.com/cds-astro/aladin-lite/blob/master/src/js/HpxImageSurvey.js#L511 and to replace 6 with a lower order (3 or 4)

This is a temporary fix of course.

**Comment by vforchi** [comment]
This has some side effects, we see other tiles popping out in places where before they didn't.

**Comment by bmatthieu3** [comment]
I close that issue because it refers to the v2.
