### ISSUE TITLE
aladin-lite not showing hips in latest firefox

### ISSUE THREAD

**Issue by havok2063** [cds-astro/aladin-lite#201]
Aladin-lite is not displaying hips images for me anymore in Firefox 131.   This link shows the issue for me https://aladin.cds.unistra.fr/AladinLite/ , but problem originally noticed in a downstream application.    

There are no obvious network errors in the dev console but I do see the following when the page loads.
`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://irsa.ipac.caltech.edu/data/hips/CDS/DSS2/color/properties. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 200.`

It works ok in Safari 17.5 and the latest Brave browser.  Maybe it's just me and I have some wonky settings?  Letting you know in case you have any browser CI tests.

**Comment by ManonMarchand** [comment]
I cannot reproduce in Firefox 131

**Comment by tboch** [comment]
hi @havok2063 , I cannot reprodce the problem either in Firefox 131, on MacOS.
The CORS message is unrelated I think.

If you look at the network tab of the developer tools, can you see the tiles being downloaded?

**Comment by bmatthieu3** [comment]
Can you check that the behavior is the same in the last released beta ?

It is used at this link:
https://aladin.cds.unistra.fr/AladinLite/doc/API/examples/show-proper-motions/

**Comment by havok2063** [comment]
Yeah I see the same behavior.

**Comment by havok2063** [comment]
I noticed I also see this message in the console `Blocked https://aladin.cds.unistra.fr/AladinLite/ from extracting canvas data because no user input was detected.`

**Comment by havok2063** [comment]
I found the issue.  I had fingerprint protection enabled in my Mozilla settings, via an extension I recently installed.  I had to disable this and now everything loads correctly.  This was under the [Enhanced Tracking Protection](https://support.mozilla.org/en-US/kb/enhanced-tracking-protection-firefox-desktop) under Browser Privacy in my Firefox settings.
