### ISSUE TITLE
catalogFromURL: alternate ra/dec columns

### ISSUE THREAD

**Issue by vforchi** [cds-astro/aladin-lite#29]
I am using the function `A.catalogFromURL` to load a catalog from tapvizier. I am using the following query to obtain the coordinates corrected by proper motion:
```
SELECT TOP 1000000 
(ra_epoch2000 + pmra*(-5.551753e-7)) as ra, 
(dec_epoch2000 + pmdec*(-5.551753e-7)) as dec, 
pmra/1000 as pmRa, pmdec/1000 as pmDec, 
ra_epoch2000 as raj2000, 
dec_epoch2000 as decj2000, 
phot_g_mean_mag as mag 
FROM "I/345/gaia2" WHERE CONTAINS(POINT('ICRS', ra, dec), CIRCLE('ICRS', 180.52643034974523, 15.34492408258429, 0.18333333333333332)) = 1 AND phot_g_mean_mag*1.0 BETWEEN 0 AND 30 ORDER BY mag ASC
``` 
The problem is that in GAIA the proper motion is null for some sources, and they are not displayed by aladin.
Unfortunately ADQL does not allow me to interpret that null as 0, as far as I know.

I tried to define a callback that goes through the sources and modifies those fields, but the sources are not displayed: I guess the callback is invoked after the sources have been drawn?

Is there a way to tell aladin to read the data from the other columns if the main ones are empty?

**Comment by vforchi** [comment]
Sorry, I was modifying `source.data.ra` instead of `source.ra`. Now it works.

**Comment by tboch** [comment]
Hi @vforchi !
Actually, you can specify the ra/dec columns to use, using the raField/decField attributes in A.catalogFromURL options. Example:
```javascript
aladin.addCatalog(
    A.catalogFromURL('https://vizier.u-strasbg.fr/viz-bin/votable?-source=HIP2&-c=LMC&-out.add=_RAJ,_DEJ&-oc.form=dm&-out.meta=DhuL&-out.max=9999&-c.rm=180',
    {raField: 'RArad', decField: 'DECrad', sourceSize:12, color: '#f08080'}));
```

**Comment by vforchi** [comment]
I know, the problem is that I generally want to use one pair, unless they are empty.
