### ISSUE TITLE
Add option A.catalogFromSimbad(...) to sort by ascending distance

### ISSUE THREAD

**Issue by tboch** [cds-astro/aladin-lite#36]
This applies when a limit has been set.

Current behaviour is to sort by decreasing number of references. This behaviour should be kept as the default.

**Comment by bmatthieu3** [comment]
A. catalogFromSimbad now query the new CS service of simbad (https://simbad.cds.unistra.fr/cone/help/#/ConeSearch/get_)

Documentation is here: https://cds-astro.github.io/aladin-lite/A.html
There is an option orderBy where you can specify different ordering based on the desc of the ORDER_BY param in the CS documentation above. 'distance' is included
