### ISSUE TITLE
Add easy access to HiPS2FITS

### ISSUE THREAD

**Issue by tboch** [cds-astro/aladin-lite#50]
Allow (in the API and the UI) access to the HiPS2FITS (https://alasky.u-strasbg.fr/hips-image-services/hips2fits ) service to retrieve a cutout of the current view, with options to choose dimensions, resolution, etc.

**Comment by bmatthieu3** [comment]
Rightclick gives a link to HiPS2FITS in which we can get the cuts of the view.
