### ISSUE TITLE
Polyline does not inherit Overlay colour

### ISSUE THREAD

**Issue by rwesson** [cds-astro/aladin-lite#53]
This behaviour can be seen in the example at https://aladin.u-strasbg.fr/AladinLite/doc/API/examples/polyline/ where the line appears white instead of the specified #ee2345. The cause is this line, where I think that `"white"` should be `undefined`:

https://github.com/cds-astro/aladin-lite/blob/64fcc777dee6435e7d98534bb1d232259cb1e5c3/src/js/Polyline.js#L40

**Comment by bmatthieu3** [comment]
This has been fixed, so I close the issue.
