### ISSUE TITLE
Background color

### ISSUE THREAD

**Issue by lmichel** [cds-astro/aladin-lite#57]
When displaying HIPS made of sparse observations and with low brightness or low featured fields,  it is very difficult to distinguish the areas covered by observations from the gaps in between observations. 

The picture below illustrates that issue with the XMM color survey in the neighborhood of Cygnus X-1

![Capture d’écran de 2022-03-23 09-18-56](https://user-images.githubusercontent.com/11462648/159654292-40b6783b-cda1-4d4f-8454-d68f591b1da1.png)

The screenshot below shows the same area displayed with Aladin Desktop. 

![Capture d’écran de 2022-03-23 09-26-18](https://user-images.githubusercontent.com/11462648/159655544-6b850821-edab-4f67-a0da-823ae92b16cc.png)

The use of a non-black gap color dramatically enhances the readability of the display.

Could this method be applied to Aladin Lite?

**Comment by bmatthieu3** [comment]
Related to #62
