### ISSUE TITLE
Default background color

### ISSUE THREAD

**Issue by lmichel** [cds-astro/aladin-lite#62]
There is a very nice feature in V3 which is the possibility of having a specific background color applied to the regions not covered by the HiPS. 
This allows to make the distinction between an area covered by the HiPS but without any visible feature and an area not covered by it.
It is also possible to choose that color.

This dramatically enhances the readability of pointed surveys such as XMM.

The issue is that the default color set by AL is black which masks the advantage of that colored background until the user find out the menu to change it.

My suggestion would be to use a default color contrasting with usual sky backgrounds, e.g. aqua blue.

**Comment by bmatthieu3** [comment]
I close this as this has been done in the v3. Background color can also be set by the user with the specific API method: https://github.com/cds-astro/aladin-lite/blob/develop/src/js/Aladin.js#L1026
