### ISSUE TITLE
Polygon cross the sky when the points located at the edge of the celestial sphere , if the projection is not SIN

### ISSUE THREAD

**Issue by xx70235** [cds-astro/aladin-lite#63]
If the projection is not SIN, there is a wrong display of polyline and polygon when points are located at different sides of the celestial sphere.

the example code:
var overlay = A.graphicOverlay({color: '#ee2345', lineWidth: 3});
aladin.addOverlay(overlay);
overlay.addFootprints([A.polygon([ [75.09706569902252, 28.254025356561616],[85.65058303267622, 29.095894440421656],[85.04345555479651, 38.3910524704836],[73.31926048625968, 37.399614744176404],[75.09706569902252, 28.254025356561616]])]);

the screenshots:
when the projection is AIT:
![WX20221029-230021](https://user-images.githubusercontent.com/1910793/198838623-ac14d7c9-5485-4141-a169-c289ff621460.png)

when the projection is SIN (which is correct)
![WX20221029-230044](https://user-images.githubusercontent.com/1910793/198838642-685a51be-f126-4f61-a8b0-5373f3e298b6.png)

**Comment by bmatthieu3** [comment]
I close it. The fix will appear soon. Feel free to reopen it if you still encounter problems.  For the moment, if there is at least one vertex from a polygon/polyline that crosses the view, then all the polygon/polyline is not displayed. Maybe we would like to only not draw the edges crossing whereas the remaining edges that lie on one side of the projection could still be displayed.
