### ISSUE TITLE
recommended workflow for custom builds

### ISSUE THREAD

**Issue by havok2063** [cds-astro/aladin-lite#64]
I'm building out a new front-end Vuejs project and would like to incorporate a custom version of AladinLite into it.  I tried building a custom version of the source code and adding it into my project, but ran into problems since the source code bundle and the `master` branch still depend on jquery and are "script-based" javacsript files, rather than importable modules.  I noticed there's an active `develop` branch focused for the new AladinLite 3.0, with many improvements, one of which seems to be a switch to importable modules with no jquery dependency.  So I'm wondering if y'all have any recommended development workflows?  How robust is this branch currently for others to develop off of, and/or how close is this branch being merged back into `master`?   Is the `develop` branch the recommended one to use for customizing AladinLite and integrating into newer front-ends built from React or Vue?  Or do you still recommend embedding AladinLite manually into html via a `script` tag?

**Comment by bmatthieu3** [comment]
Hi @havok2063,

As of today, branch develop is where all the major features are developed and it has already been merged into master a couple months ago when the aladin lite v3 has been released.

I link @ggreco77 to that issue because his team developped an aladin lite react component, maybe you can talk with him.
Also, we are trying to make a npm package out of aladin lite we help is really wanted as we do not have lot of experience doing that ( #77 )

**Comment by havok2063** [comment]
@bmatthieu3 Thanks for the update.  I will play around with the new 3.0 release and see if I can get it working the way I need.  I found this package already on npm, https://www.npmjs.com/package/aladin-lite, created a few months ago.  Does this work or are you still having troubles with creating an npm package?  It looks like this still requires aladin-lite to be used as a script?  I guess the next step would be to get aladin-lite working as an importable module, which is indeed related to #77.

**Comment by bmatthieu3** [comment]
It was a testing package I made a few months ago but did not work on my side. I agree one would like to just npm install aladin-lite and in his script, without importing the aladin lite script, just do:

```js
import {A} from 'aladin-lite';

A.init.then(() => {
    let aladin = A.aladin(...)
})
```

**Comment by bmatthieu3** [comment]
Implemented in https://github.com/cds-astro/aladin-lite/pull/93, open a new issue if you see something else to do regarding the npm package.
