### ISSUE TITLE
Version 3 re-write in Typescript: the dawn of Aladin.ts?

### ISSUE THREAD

**Issue by michealroberts** [cds-astro/aladin-lite#67]
Hi to the maintainers of this repo. 👋 

One thing I have been thinking of implementing for a while is a re-write of Aladin lite in Typescript, which can be embedded from either a CDN or imported as `import Aladdin from 'aladdin'` or similar.

Would this be something of merit to the maintainability of the project?

**Comment by bmatthieu3** [comment]
Hi @michealroberts ,

That would be very great to do this as it could also be maybe easier to create an npm package from it as well. I have not a big experience coding in Typescript. Theredore, do you know, maybe tutorials or resources that would be useful to someway create a typescript wrapper around the js current Aladin Lite code ? (That would certainly be easier than re-write the whole Js into Typescript). Thanks,

**Comment by michealroberts** [comment]
Hi @bmatthieu3 So I have coded in JS for over 14 years ... and Typescript for 4 of those, I would be more than comfortable in directing these efforts if that suits ... I think we could write type definition, but sometimes it is far more maintainable to re-write in TS ... I could prepare an RFC for this process ...

**Comment by bmatthieu3** [comment]
Hi @michealroberts ,
For me and @tboch it seems that a full TS rewrite is a very heavy task to do (there are at this time approx. 25k lines of JS inside Aladin Lite right now) whereas the alternative option you mention (type definition files) is much more reasonable, especially if it allow to release a npm package from that more easily (which is a very nice goal to have for our plans).

In other hands, the bigger the 'feature necessity' over the 'time to do it' ratio is, the higher this task would be in the task priority list.

If you would like to help us doing this (the type definition files), we would be of course very happy and could help too.

**Comment by michealroberts** [comment]
Hi @bmatthieu3 Apologies for my late reply to this.

I certainly agree, a total re-write is never something you want to do lightly and type definition files would be a step in the right direction.

The pros to a total re-write are that we know that what we write is 100% typesafe and correct with modern standards - so we can deploy with much more confidence (combined with a test suite this could work really nicely).

The cons are time, and loosing focus and loosing steam.

Perhaps, are there smaller modules that we can migrate away one at a time ... and at least then we can incrementally look to move to TS? We could perhaps leverage a monorepo technology like Nx or Turbo to handle the complexity, and then swc or similar for compilation between modules. This may then provide us with a safer route to achieving a "full re-write". Do you think this approach could work in the long run?

**Comment by onekiloparsec** [comment]
Please have a look at the PR #111 I've just submitted. Going for a mono-repo is totally unnecessary IMHO. We can make a smooth transition to TS file after the other.

Likewise, I've introduced Vitest to start writing unit tests, and removed a dependency of jQuery on once place. First steps towards a cleaner and safer codebase without jQuery dep.

**Comment by michealroberts** [comment]
I think the phrase totally unnecessary in respects to a monorepo is a bit harsh. A monorepo would be a good way to organise such a large complex codebase, compartmentalising into core packages, as well as plugins and adapters for modern frontend frameworks like Vue / react / svelte / solid et al. 

All of the major JS / TS libraries have moved to monorepos. I certainly wouldn't advocate for a complete migration, but starting to think about where code sits in respect to their layer, whether that be utility, domain, core or presentational, would be advantageous. Coupling with modern tooling like turbo would also speed up actions with intelligent caching per module / package.

I think the long term roadmap of giving Aladin a sustainable foundation going into the next 10 years of developer should certify bare this in mind. Happy to answer any more questions! :)

**Comment by ManonMarchand** [comment]
Just on the side of ipyaladin, could we plan a test before merging the PR @bmatthieu3 ?
(I was also thinking that one day we should switch to the tyescript cookiecutter which is better maintained than the JS one... could this be an opportunity? )

**Comment by onekiloparsec** [comment]
Two more additional cents. Although I wish Aladin could also have solid foundations for the next 10 years, I think it is good to start from what it is today. 25k lines is not a large codebase, hence I don't see the real added-value of a big bang changing the whole structure of the repo. Moreover, the maintainer team is small, mostly with scientific background, as far as I can tell etc.

As for the cookiecutter, why not. But it is mostly useful when you _start_ a project, IMHO, not when a codebase is already in place.

Personally, my vision of the Aladin codebase was to keep it as it is today: a JS library. Simply migrating slowly to Typescript, while the features are being improved as well. Hence my PR. :-)

**Comment by tboch** [comment]
I'm not sure I fully understand all the arguments put forward in this issue, but let me say I'm not at ease with making a big change to the project structure. 
Incremental small changes have my preferences.

**Comment by ManonMarchand** [comment]
Sorry, you needed context for that, I'm only talking about the widget version here : https://github.com/cds-astro/ipyaladin which is based on ipywidgets and would benefit from following the TS cookiecutter changes rather than guessing how to port things anytime something changes in the jupyter ecosystem :)

**Comment by onekiloparsec** [comment]
I am not familiar with the code of `ipyaladin`, and I don't know how a coockiecutter could be used. But I'll be happy to adapt the PR for that if needed. 

Note that my PR really has almost no effect. It changed only two files from JS to TS, and added a test framework. However, I haven't tested the outcome of the builds.

**Comment by bmatthieu3** [comment]
I will close that issue because:
* There is now a NPM package allowing you to import aladin lite the ES way: https://www.npmjs.com/package/aladin-lite and it did not involve to rewrite something in TS for that.
* jQuery is now completely removed from the project

Feel free to reopen it if something still need to be discussed

**Comment by onekiloparsec** [comment]
Thanks Matthieu for the bookkeeping. I agree there is no technological obligation to rewrite everything in TS, although it would improve the quality of the JS part, in my opinion. I wish I could have more time...

**Comment by michealroberts** [comment]
Appreciate the move to ESM. Likewise, when I get time I will attempt to port some aspects of the code to TypeScript. I am wondering if we could potentially start with JS docs a la Svelte, and slowly adopt some typing. I will investigate this further! 🔭
