### ISSUE TITLE
Instructions to build minified version

### ISSUE THREAD

**Issue by simontorres** [cds-astro/aladin-lite#77]
I'm integrating Aladin lite in a React application with Typescript. It works OK. The only problem that I'm having is to package my app, because of the way Aladin is provided, not a package, the build process fails because "typescript cannot find the A object" which by the way is not exported in Aladin therefore can't be imported.

My idea to to add an `export default A` statement to the Aladin.js file and rebuild the minified aladin.js file. So I can place it in my package and import from there. Is this even possible? I'm relatively new to packaging javascript so I'm guessing the solution should be relatively simple. Thanks in advance.

**Comment by tboch** [comment]
I guess this should work fine, yes.
Note that we plan to provide with a npm package.

**Comment by simontorres** [comment]
Having the npm package would be awesome, do you have an estimated time to when this will be available. I would help me a lot to know in order to plan my work ahead.

Thanks!

**Comment by bmatthieu3** [comment]
Hi @simontorres,

We want that to be a priority feature to implement. However we encounter some difficulties doing it. Using the export line does not seem to do the trick. I have seen maybe a 'type': module entry must be added to the package.json but after doing so I still have troubles importing A and Aladin from module/npm package created.

In other words, if someone has more experience into npm packaging, that would be very interesting for us to learn more from that person.

I add the tag 'help wanted' to that issue.

**Comment by simontorres** [comment]
@bmatthieu3 Thanks a lot for trying this out. I'm sure this feature would be very useful for many teams. I have talked to @diego-ge in my team who has a lot of experience with this and has agreed to take a look.

In the meantime, have you tried exporting `A` like this?

```javascript
module.exports = A
```

**Comment by bmatthieu3** [comment]
@simontorres @diego-ge many thanks for looking at it! I added the line but I am not sure how I could test that afterwards before publishing it.

**Comment by simontorres** [comment]
@bmatthieu3 I tried the same myself and it seems that is webpack the responsible to manage what the library finally exports. I know that webpack is somewhat a less favored tool, so I would like to try with other tool and see wether it is a lot of work simple to migrate. Hopefull @diego-ge could give us his feedback.

**Comment by bmatthieu3** [comment]
I have heard there is something called Vite, maybe I can invest some time in that

**Comment by cquiroz** [comment]
We are using Vite successfully with a modified version of aladin that exports packages as es modules

**Comment by parkma99** [comment]
> 

Could you give me some examples? Thank you😉😉

**Comment by diego-ge** [comment]
@bmatthieu3 I like the Idea.
Yesterday I was able to compile everything using Vite instead of webpack, but I'm having an error after creating the aladin instance using `A.init.then`
Specifically I got
`ERROR: 0:15: '@' : invalid character
ERROR: 0:15: 'include' : syntax error
` 

It looks like the following line is giving the error, even after I checked elapsedTime was an integer number
`this.wasm.update(elapsedTime);`

**Comment by bmatthieu3** [comment]
Ah I also encountered this error. This is something related to the bundle of glsl files (gpu files). The vite plugin for that, contrary to the one of webpack handles the inclusion of glsl files with the syntax '#include <name of the file>.glsl;' instead of '@include <name of the file>.glsl'.
In the PR I fixed that.

**Comment by bmatthieu3** [comment]
Implemented in #93, open a new issue if you see something else to do regarding the npm package.
