### ISSUE TITLE
Slower Switching between Image Surveys

### ISSUE THREAD

**Issue by bmiszalski** [cds-astro/aladin-lite#88]
The new Aladin Lite v3 is fantastic. 
I've noticed however that if I have several surveys loaded up already, that switching between them appears slower than in v2. 
In v2 it is almost instant. 
In v3 there appears to be a 'fade-in' effect that comes with loading a different Image Surveys (e.g. via aladin.setImageSurvey('label')). 
This can be problematic in apps that need to quickly switch between different images.

Is it possible to remove this delay? 
Perhaps it's an intrinsic feature of wasm? 
If the delay could be reduced, perhaps a delay parameter could be introduced to the options that could be set to zero?

Another explanation might be that Aladin.prototype.setOverlayImageLayer might create new Image Surveys when called, when this function could instead be checking through aladin.cacheSurveys.get('label') for an existing one.
I've tried to bypass the calls to this.createImageSurvey in Aladin.prototype.setOverlayImageLayer but did not get too far.
Any ideas?

**Comment by bmatthieu3** [comment]
@bmiszalski - There is a fade-in effect which takes place during a few 100s milliseconds/1sec once all the base tiles do have been received (either the 12 order 0 base tiles or the allsky file from which the 12 order base tiles can be created). Every time the user wants to switch these files are fetched and if they are related to fits tiles and depending on the network quality it can be slow. I suppose this is the time to fetch the tiles that is long (> to the fade-in effect time duration) ?

Appart from that, there is a request to fetch the properties of the HIPS to get all the information about the HiPS (given an url or an HiPS ID). This request can be avoided, I will create a pull request to cache de ImageSurvey object instead in cacheSurveys, maybe this can reduce the delay. If it is still not enough, maybe one should cache de base order tiles (wasm code) to avoid the base tiles/allsky requests.

**Comment by bmatthieu3** [comment]
here is the PR: #89 maybe you can test on your side to see if the behaviour is a little better. More things to do would be:
* cache de base tiles textures (wasm code) to not request them
* reduce the 1sec duration fade-in effect

**Comment by bmiszalski** [comment]
Merci beaucoup Matthieu! 
It feels noticeably fast now. Indeed, I noticed that loading a HiPS with imgFormat: 'png' was faster than 'fits', but then the scale (via right mouse btn) could not be adjusted.
I'm not sure whether it's worth trying to cache the textures, but reducing or removing the 1 sec duration fade-in effect would be better. 
Do you know how might I do that? Can it be set to zero?
Best regards,
Brent.

**Comment by tboch** [comment]
I noticed this delay as well, and it's indeed disturbing when switching HiPS.
I like however the fade-in effect once the HiPS is loaded and when I zoom in for instance.

**Comment by bmiszalski** [comment]
Hi @bmatthieu3, Happy New Year! I was wondering whether any progress might have been made for this ticket? 
If it might be a relatively straightforward task to remove the delay (?), I'd be happy to test the fix.
Best regards,
Brent.

**Comment by bmatthieu3** [comment]
Hi @bmiszalski , there is npm beta package. Can you test it on your side and tell me if things are starting a little faster ?

**Comment by bmatthieu3** [comment]
I will close that issue, I think that it has been enhanced here: c2bb0980af4d88d93af4c7a27efb96e2a233b2da + the time for an aladin lite instanciation has been fasten too. If you still experience some issues, please reopen the issue or feel free to create a new one.
