### ISSUE TITLE
Clarify your branch model?

### ISSUE THREAD

**Issue by onekiloparsec** [cds-astro/aladin-lite#96]
Hi,

I have some difficulty to create a simple pull request for this project, because I don't understand clearly the model of branches. Could you clarify / rearrange ? 

Things I don't understand:

- The role of branch `deploy` ? Was it for exploration of deployments, or a kind of a replacement of `master` ? I see a tag has been set on that branch (two of them actually: 3.1.0 and 0.3.1 on the same commit...)
- Given the number of branches and contributors, does `master/develop` kind of git flow really necessary? I am usually in favor of a `develop` branch, but it makes more sense for larger projects.
- I would like to use content of the `vite` branch, which is apparent merged in this [PR](https://github.com/cds-astro/aladin-lite/pull/93). But it doesn't appear like that in the history ??

A few suggestions:
- Merge the `develop` branch into `master` once for all, and delete `develop`.
- Rename all _active_ feature branches with ` common prefix `feature/` (the slash is nice for git client to create folders)
- Delete merged/inactive branches
- Rename exploratory or legacy branches with corresponding prefixes.

It would help the small "community" to actually enter the project, and participate, IMHO. I am willing to provide help for CI, GH action, vite, vitest (Jest-equivalent test lib) and other JS/TS stuff.

Thanks a lot!

**Comment by bmatthieu3** [comment]
Hi,

Thanks for the hints, I like all your suggestions apart the one removing the develop branch. A develop is good to run tests under it before merging to master. We had experiences of feature merging that can create unreleated test failures.
The deploy branch should only be local, it is for deploying the code into our servers.

Thanks for willing to contribute to the CI.

**Comment by onekiloparsec** [comment]
Thanks for the quick response Matthieu.

Of course running test before release is always good. I am not familiar with the current status, but of course, release can either be on every:
- **push** to `master`, and in that case, you need a `develop` branch to land all features before merging (your model, as far as I understand)
- **tag** to `master`. In that case, no need for `develop`, and you "merge" the release with the creation of a tag.

If you prefer to stick to the first case, no problem. So then I will make PR on `develop`. Note that you nonetheless need to run test also on the `develop` branch, IMHO.

I am still surprised with the role of the `deploy` branch. You say it is for internal use in CDS. But having a separate branch is forcing you to maintain and rebase it, right? I see this more like a special case of the release. Hence I would personally add a special section in the release process that is activated only in the presence of a given local information, such as a secret environment variable or so.

But I am not in CDS, I can't help. 

What about the `vite` branch ? If I checkout `develop` today, it is still using webpack...

Thanks again!

**Comment by bmatthieu3** [comment]
Yes the first point is what we are (trying) to do. All the features/PR points to the develop and after a while it is merged to the master.

For the deploy branch, I think that there has been a time where I accidentally did push it remotely but actually it should not be a remote branch. I think it has one commit that I indeed rebase when I want to deploy it to the CDS server. Thanks for  having pointing that to us!

For the vite branch, I am not sure I understand, the vite branch has been merged recently to the develop (looking at that PR):
https://github.com/cds-astro/aladin-lite/pull/93
Even on the github interface if I go on the develop branch, I can see there is the 'vite.config.js' at the root of the repo so it seems to have been merged. Maybe you can try a git fetch on your side or pull directly from your local develop branch ?

**Comment by onekiloparsec** [comment]
I must have mixed myself with an existing fork that was not up-to-date. I see now the clean `develop` branch with the vite config. And I see branches have been cleaned up as well. Thanks!
