### ISSUE TITLE
Hover effects on shapes

### ISSUE THREAD

**Issue by imbasimba** [cds-astro/aladin-lite#98]
I would like to have hover effects on all clickable shapes, i.e. making the shape brighter and potentially changing the cursor to a pointer.
This old pull request https://github.com/cds-astro/aladin-lite/pull/41 partially addresses this issue, but this should also be extended to MOC shapes.

**Comment by bmatthieu3** [comment]
Does the 'objectHovered' callback (extended to MOC shapes, maybe pro) could be sufficiant for you to tweak the color, thickness, whatever ?
